---
title: "Eleccion de m por menor sesgo promedio"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(ggplot2)
library(data.table)
require(ggthemes)
library(extrafont) 

```

```{r}
L= 2
m_por_sesgo<-fread("../../../Data/CISS2021/Figura2.csv")

names(m_por_sesgo)

```

# Grafico


```{r}


g1<- m_por_sesgo %>% filter(L==L,Estimator!="MH",Estimator!="HE",Estimator!="HMV.mle")

g1$alfa <- factor(g1$alfa, levels = c("-1.5","-3","-5","-8"),
                         ordered = TRUE,
                  labels=c(expression(alpha==-1.5),
                  expression(alpha==-3),
                  expression(alpha==-5),
                  expression(alpha==-8))
                  )
legenda <- c(expression(widehat(italic(H))[A0[1]]),
             expression(widehat(italic(H))[C]),
             expression(widehat(italic(H))[ML]),
             expression(widehat(italic(H))["NA"]),
             expression(widehat(italic(H))[V]),
             expression(widehat(italic(H))[VE]))

plt1<-ggplot(g1,aes(n,Bias,col=Estimator))+
scale_x_continuous(breaks=c(9,25,49,81,121))+
geom_hline(yintercept=0, linetype="solid", color = "blue",size=1)+
geom_point()+
geom_line()+
labs(x = "sample size",y=expression(paste(widehat(Bias))))+
scale_color_discrete(name="Estimator",labels = legenda)+
theme(text=element_text(size=12, family="serif"),
      legend.position = "bottom",
      strip.background =element_rect(fill="white"),
      strip.placement = "outside",
      strip.text = element_text(size=10),
      legend.title = element_text(size = 10),
      legend.text = element_text(size = 10),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill=NA)) +
      guides(colour = guide_legend(nrow = 1))+
facet_wrap(~alfa, labeller = label_parsed)
plt1
ggsave(plot=plt1, file="../../../Figures/CISS2021/Grafico_Hest_Sesgo_L=2ConNeg.pdf", width=12, height=12, units="cm")

```

```{r}
plt2<-ggplot(g1,aes(n,MSE,col=Estimator))+
scale_x_continuous(breaks=c(9,25,49,81,121))+
geom_hline(yintercept=0, linetype="solid", color = "blue",size=1)+
geom_point()+
geom_line()+
labs(x = "sample size",y=expression(paste(widehat(MSE))))+
scale_color_discrete(name="Estimator",labels = legenda)+
theme(text=element_text(size=12,  family="serif"),
      legend.position = "bottom",
      strip.background =element_rect(fill="white"),
      strip.placement = "outside",
      strip.text = element_text(size=10),
      legend.title = element_text(size = 10),
      legend.text = element_text(size = 10),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill=NA)) +
      guides(colour = guide_legend(nrow = 1))+
facet_wrap(~alfa, labeller = label_parsed)
plt2
ggsave(plot=plt1, file="../../../Figures/CISS2021/Grafico_Hest_ECM_L=2ConNeg.pdf", width=12, height=12, units="cm")

```


```{r}

graf.alfa<-paste("Grafico_Hest_Sesgo_L=",L,"ConNeg.pdf",sep = "")
graf.ecm<-paste("Grafico_Hest_ECM_L=",L,"ConNeg.pdf",sep = "")



ggsave(graf.alfa, plot = plt1, device = "pdf",scale=1.2)
ggsave(graf.ecm, plot = plt2, device = "pdf",scale=1.2)
```






